// The folio is not a static asset and never becomes one. If it lived in
// dist/ the password would be theatre: anyone could fetch the file directly
// and read it. So it is compiled into the worker bundle instead, where the
// only way out is through the gate.
//
// The source sits under /contents, which is gitignored, and so is the module
// written here. Neither reaches the public repo. A fresh clone without the
// source still builds: the stub makes /names answer 404, which is the honest
// answer when there is nothing to serve.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const SRC = "contents/updated media/poetic-name-folio.html";
const OUT = "worker/names-folio.js";

if (!existsSync(SRC)) {
  writeFileSync(OUT, "// no folio source present at build time\nexport default null;\n");
  console.log("names: no source, /names will 404");
} else {
  const html = readFileSync(SRC, "utf8");
  writeFileSync(OUT, `// generated by scripts/names-build.mjs — do not edit, do not commit\nexport default ${JSON.stringify(html)};\n`);
  console.log(`names: folio compiled in, ${(html.length / 1024).toFixed(1)}kb`);
}
